name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setup Chrome Remote Desktop
      run: |
        choco install googlechrome -y
        choco install chrome-remote-desktop-host -y

    - name: Start Chrome Remote Desktop
      run: ./tess.ps1
    - name: Time Counter
      run: Start-Sleep -Seconds 10800
